"""Add university_id column

Revision ID: 5936ba3513d7
Revises: 
Create Date: 2025-02-19 05:38:58.313741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5936ba3513d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('university_id', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['university_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('university_id')

    # ### end Alembic commands ###
